### PR TITLE
Add how to pipeline

### PR DESCRIPTION
**Pull request by motoki0813**
how-to-pipelineを記事にしました！

### CODE REVIEW

**Comment by fyuuhi** [comment]
注意事項として、以下もブログに追加
https://marketplace.visualstudio.com/items?itemName=Dyn365FinOps.dynamics365-finops-tools
Known Limitations and Issues
LCS Authentication requires AAD accounts that do not have MFA enabled, and are not backed by federated logins. We are reviewing options for new authentication features in LCS that can enable the API and these tasks to authenticate under such setups, such as service-to-service authentication.

**Comment by fyuuhi** [comment]
可能ならUIを全部英語 (low priority)

**Comment by fyuuhi** [comment]
https://github.com/motoki0813/blog/blob/add-how-to-pipeline/articles/D365FO%20Tech/how-to-pipeline/CreatePipe2.png
https://github.com/motoki0813/blog/blob/add-how-to-pipeline/articles/D365FO%20Tech/how-to-pipeline/CreateFeed2.png
の左上のproject名が不一致

**Comment by fyuuhi** [comment]
全体的に図が多いので、可能なら、図に枠線付けた方が見やすい
https://mlog.wlaboratory.com/entry/category/languages/markdown/add-border-to-image

**Comment by motoki0813** [comment]
現段階で写真以外の修正は完了しました、その他ご指摘などございましたらお願いいたします

**Comment by motoki0813** [comment]
一旦消します

**Pull request closed without merging**
